name: Build And Push Budget Tracker App

on:
  release:
    type: [published]
  push:
    branches: [ "main" ]

  env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    env:
      CONFIGURATION: development

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          package_json_file: ./budget-tracker-frontend/package.json

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: ./budget-tracker-frontend/package-lock.json

      - name: Build SPA frontend
        working-directory: ./budget-tracker-frontend
        run: |
          pnpm install --no-frozen-lockfile
          if [ ${{ env.CONFIGURATION }} == "development" ]; then
            echo "Building development version"
          else
            echo "Building production version"
          fi
      - name: Extract release version
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "RELEASE_VERSION=$TAG_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/budget-tracker:$RELEASE_VERSION .
          docker tag $DOCKERHUB_USERNAME/budget-tracker:$RELEASE_VERSION $DOCKERHUB_USERNAME/budget-tracker:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKERHUB_USERNAME/budget-tracker:$RELEASE_VERSION
          docker push $DOCKERHUB_USERNAME/budget-tracker:latest